### ISSUE TITLE
Number not found if follow by .

### ISSUE THREAD

**Issue by internetboekhandel** [pickware/address-splitter#19]
This address cannot be split:
Test street 20. 2. house 1.

The . after the number makes it fail, remove anyone of the number it will work. (somewhat)

**Comment by svenmuennich** [comment]
Can you please provide a PHP snippet containing the address string and the expected result, so that we can add it to the unit tests to be able to develop a fix? E.g.:

```php
array(
    '3940 Radio Road, Unit 110',
    array(
        'additionToAddress1' => '',
        'streetName'         => 'Radio Road',
        'houseNumber'        => '3940',
        'additionToAddress2' => 'Unit 110'
    )
)
```

**Comment by antoniokupresak** [comment]
This bug has been fixed somewhen in the past. Closing here.
