### ISSUE TITLE
parse error when street starts with 'No...'

### ISSUE THREAD

**Issue by BrentVanhooren** [pickware/address-splitter#30]
When parsing an address, following error is thrown when the street name starts with 'No'. Most likely this occurs because the parser is expecting a number after this letter combination.

`Address 'Nolimpark 4004' could not be splitted into street name and house number.`

**Comment by svenmuennich** [comment]
Thanks for reporting this bug.

This is a regression introduced by b434d98a482adc259e98f8be79b38c6ef12fe52d and will be fixed by #29 soon.

**Comment by cjuner** [comment]
The fix has been released and published to Packagist in version 0.3.4:

* Packagist: <https://packagist.org/packages/viison/address-splitter#0.3.4>
* GitHub release page: <https://github.com/pickware/address-splitter/releases/tag/0.3.4>
